export const MODULES = [
  { key: 'dashboard', label: 'Dashboard', path: '/' },
  { key: 'products', label: 'Productos', path: '/products' },
  { key: 'presentation-types', label: 'Tipos de Presentacion', path: '/presentation-types' },
  { key: 'categories', label: 'Categorías', path: '/categories' },
  { key: 'payment-methods', label: 'Métodos de Pago', path: '/payment-methods' },
  { key: 'company-settings', label: 'Mi Empresa', path: '/company-settings' },
  { key: 'inventory', label: 'Inventario', path: '/inventory' },
  { key: 'sales', label: 'Ventas', path: '/sales' },
  { key: 'cash-register', label: 'Caja', path: '/cash-register' },
  { key: 'cash-movements', label: 'Movimientos de Caja', path: '/cash-movements' },
  { key: 'cash-reports', label: 'Reporte de Cajas', path: '/cash-reports' },
  { key: 'product-movements', label: 'Movimientos de Productos', path: '/product-movements' },
  { key: 'alerts', label: 'Alertas', path: '/alerts' },
  { key: 'customers', label: 'Clientes', path: '/customers' },
  { key: 'reports', label: 'Reportes', path: '/reports' },
  { key: 'returns', label: 'Devoluciones', path: '/returns' },
  { key: 'suppliers', label: 'Proveedores', path: '/suppliers' },
  { key: 'purchases', label: 'Compras', path: '/purchases' },
  { key: 'scan-qr', label: 'Escanear QR', path: '/scan-qr' },
  { key: 'users', label: 'Usuarios', path: '/users' },
] as const;
